[provider]
cluster = "mainnet"
wallet = "../bilc.json"

[provider.mainnet]
url = "https://mainnet.helius-rpc.com/?api-key=ca49b73e-00a4-42d0-8e60-ad1a01e3dc97"

[workspace]
exclude = ["programs/openbook_v2"]

[scripts]
# to run local validator tests, use "./test-scripts/run-ts-mocha" in "test"
test = "echo" # need to call anchor test to update metadata field in idl before running tests, so just do a noop
lint = "yarn prettify:fix && cargo fmt"
fulltest = 'cargo test && bash ./test-scripts/run-anchor-tests.sh'
watch_ts = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c bash ./test-scripts/single-anchor-test.sh'
watch_build = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c anchor build'
watch_cargo = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c cargo test -- --show-output'

[programs.mainnet]
drift = "7a247Z1uc66BycPHmL7xuGps2Jrym9RQngiWwgqQCtYn"
pyth = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"
token_faucet = "5mnk7fV1JRfsr2jqVCb8yrw4mKByEQcJkGXRUXguc1TE"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "./deps/configs/usdc.json"

[[test.validator.account]]
address = "3rdJbqfnagQ4yx9HXJViD4zc4xpiSqmFsKpPuSCQVyQL"
filename = "./deps/configs/pyth_lazer_storage.json"